name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v4
          with:
            node-version: '14.x'
        - name: Install
          run: npm install
        - name: Test
          run: npm run test